export const GET_ALL_APPOINT_PATIENT_REQUEST = "GET_ALL_APPOINT_PATIENT_REQUEST";
export const GET_ALL_APPOINT_PATIENT_SUCCESS = "GET_ALL_APPOINT_PATIENT_SUCCESS";
export const GET_ALL_APPOINT_PATIENT_FAIL = "GET_ALL_APPOINT_PATIENT_FAIL";


export const APPOINT_PATIENT_REQUEST = "APPOINT_PATIENT_REQUEST";
export const APPOINT_PATIENT_SUCCESS = "APPOINT_PATIENT_SUCCESS";
export const APPOINT_PATIENT_FAIL = "APPOINT_PATIENT_FAIL";
export const APPOINT_PATIENT_RESET = "APPOINT_PATIENT_RESET";


export const GET_ALL_PRESC_REQUEST = "GET_ALL_PRESC_REQUEST";
export const GET_ALL_PRESC_SUCCESS = "GET_ALL_PRESC_SUCCESS";
export const GET_ALL_PRESC_FAIL = "GET_ALL_PRESC_FAIL";


export const GET_last_PRESC_REQUEST = "GET_last_PRESC_REQUEST";
export const GET_last_PRESC_SUCCESS = "GET_last_PRESC_SUCCESS";
export const GET_last_PRESC_FAIL = "GET_last_PRESC_FAIL";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";


export  const CLEAR_ERRORS="CLEAR_ERRORS"