export const CONTACT_REQUEST = "CONTACT_REQUEST";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CONTACT_RESET = "CONTACT_RESET";

export const VIDEO_REQUEST = "VIDEO_REQUEST";
export const VIDEO_SUCCESS = "VIDEO_SUCCESS";
export const VIDEO_FAIL = "VIDEO_FAIL";



export  const CLEAR_ERRORS="CLEAR_ERRORS"