export const GET_ALL_REGISTER_PATIENT_REQUEST = "GET_ALL_REGISTER_PATIENT_REQUEST";
export const GET_ALL_REGISTER_PATIENT_SUCCESS = "GET_ALL_REGISTER_PATIENT_SUCCESS";
export const GET_ALL_REGISTER_PATIENT_FAIL = "GET_ALL_REGISTER_PATIENT_FAIL";


export const REGISTER_PATIENT_REQUEST = "REGISTER_PATIENT_REQUEST";
export const REGISTER_PATIENT_SUCCESS = "REGISTER_PATIENT_SUCCESS";
export const REGISTER_PATIENT_FAIL = "REGISTER_PATIENT_FAIL";
export const REGISTER_PATIENT_RESET = "REGISTER_PATIENT_RESET";


export  const CLEAR_ERRORS="CLEAR_ERRORS"